name: Rosetta Release

on:
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.13.0'
        
      - name: Checkout rosetta
        uses: actions/checkout@v2
        with:
          repository: leeheonseung/rosetta-icon
          ref: main
      
      - name: Install packages
        run: go get .
        
      - name: Build
        run: make
