name: Rosetta Release

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.13.0'
        
      - name: Checkout rosetta
        uses: actions/checkout@v2
        with:
          repository: leeheonseung/rosetta-icon
          ref: main

      - name: Install packages
        run: go get .
      
      - name: Check
        run: pwd
      
      - name: Build
        run: make

      - name: Upload Executable
        uses: actions/upload-artifact@v1
        with:
          name: rosetta-icon
          path: ./bin/rosetta-icon
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Download Executable
        uses: actions/download-artifact@v2
        with:
          name: rosetta-icon
