name: Rosetta Release

on:
  push:
    tags: 
      - '*'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.13.0'
        
      - name: Checkout rosetta
        uses: actions/checkout@v2

      - name: Install packages
        run: go get .
      
      - name: Check
        run: pwd
      
      - name: Build
        run: make

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.RELEASE_SECRET }}
          file: bin/rosetta-icon
          asset_name: Rosetta-ICON
          tag: ${{ github.ref }}
          overwrite: true
          body: "Rosetta-ICON"
  tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Executable
        uses: actions/download-artifact@v2
        with:
          name: Rosetta-ICON
